name: my_cmfi_app
description: "My CMFI App"

publish_to: "none"

version: 1.0.0+1

environment:
  sdk: ">=3.4.4 <4.0.0"

dependencies:
  cached_network_image: ^3.4.1
  envied: ^1.2.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_svg: ^2.0.16
  freezed_annotation:
  go_router:
  google_fonts: ^6.2.1
  hooks_riverpod: ^2.6.1
  intl: any
  json_annotation: ^4.9.0
  logging: ^1.3.0
  riverpod_annotation: ^2.6.1
  share_plus: ^10.1.3
  shared_preferences:
  slang:
  slang_flutter:
  flutter_hooks:
  supabase_flutter: ^2.9.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  mocktail_image_network: ^1.2.0
  mocktail: ^1.0.4
  integration_test:
    sdk: flutter
  build_runner: ^2.4.13
  slang_build_runner:
  freezed:
  json_serializable:
  custom_lint:
  riverpod_generator: ^2.6.1
  riverpod_lint: ^2.6.1
  envied_generator: ^1.1.1
  # lean_builder:

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/images/2.0x/
    - assets/images/3.0x/
    - assets/icons/
    - assets/icons/2.0x/
    - assets/icons/3.0x/
